# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# SpecialOverlay.py
# Created on: 2014-04-15 15:57:36.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: SpecialOverlay <grid> <over> 
# Description: This special tool will append data from one file to another. 
# This tool was create with a pinch of love, and a dash of magic. 
# He truly is a blessing. 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Script arguments
grid = arcpy.GetParameterAsText(0)
if grid == '#' or not grid:
    grid = "grid" # provide a default value if unspecified

over = arcpy.GetParameterAsText(1)
if over == '#' or not over:
    over = "over" # provide a default value if unspecified

# Local variables:
grid__2_ = grid
grid__4_ = grid__2_
grid_Identity = grid__4_
grid_Identity__2_ = grid_Identity
grid_Identity__3_ = grid_Identity__2_
grid_Identity__6_ = grid_Identity__3_
grid_Identity__4_ = grid_Identity__6_
over_SpatialJoin = grid_Identity__4_

# Process: Add Field
arcpy.AddField_management(grid, "AREA", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(grid__2_, "AREA", "!shape.area@squaremeters!", "PYTHON_9.3", "")

# Process: Identity
arcpy.Identity_analysis(grid__4_, over, grid_Identity, "NO_FID", "", "NO_RELATIONSHIPS")

# Process: Add Field (2)
arcpy.AddField_management(grid_Identity, "RATIO", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(grid_Identity__2_, "RATIO", "!SHAPE_Area! / !AREA!", "PYTHON_9.3", "")

# Process: Add Field (3)
arcpy.AddField_management(grid_Identity__3_, "NEWVAL", "FLOAT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(grid_Identity__6_, "NEWVAL", "!VAL! * !RATIO!", "PYTHON_9.3", "")

# Process: Spatial Join
arcpy.SpatialJoin_analysis(over, grid_Identity__4_, over_SpatialJoin, "JOIN_ONE_TO_ONE", "KEEP_ALL", "ID \"ID\" true true false 2 Short 0 0 ,First,#,U:\\Taylor\\SpecialOverlay\\SpecialOverlay.gdb\\grid_Identity,ID,-1,-1;AREA \"AREA\" true true false 4 Float 0 0 ,First,#,U:\\Taylor\\SpecialOverlay\\SpecialOverlay.gdb\\grid_Identity,AREA,-1,-1;RATIO \"RATIO\" true true false 4 Float 0 0 ,First,#,U:\\Taylor\\SpecialOverlay\\SpecialOverlay.gdb\\grid_Identity,RATIO,-1,-1;NEWVAL \"NEWVAL\" true true false 4 Float 0 0 ,Sum,#,U:\\Taylor\\SpecialOverlay\\SpecialOverlay.gdb\\grid_Identity,NEWVAL,-1,-1", "CONTAINS", "", "")

